on:
  pull_request:
    types: [opened, synchronize]

name: Test

jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: "[INFO] Versions"
        run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"

      - name: Install packages
        run: >-
          yarn install
          --frozen-lockfile
          --ignore-optional
          --no-progress
          --non-interactive

      - name: Test
        run: yarn test
